<Project>
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <Optimize Condition="'$(Configuration)' == 'Release'">true</Optimize>
        <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
        <Deterministic>true</Deterministic>
        <Authors>DroneOps</Authors>
        <Product>DroneOps Playground</Product>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
        <DefineConstants>DEBUG;TRACE</DefineConstants>
    </PropertyGroup>
</Project>
